# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
def shared_pods

pod 'Alamofire', '~>4.0.1'
pod 'SwiftyJSON', '~>3.1'
pod 'ObjectMapper', '~> 3.2'
end

target 'Swift-iOS-Template DEV' do
  shared_pods
end

target 'Swift-iOS-Template PRODUCT' do
shared_pods
end

target 'Swift-iOS-Template STAGING' do
shared_pods
end
